# fly.toml app configuration file generated for rbravo on 2024-01-05T16:26:02-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rbravo"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/resources/healthcheck"